<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MotorVarSpeed_FB" Id="{e9de67a0-f478-4523-bff0-bbe131d76573}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MotorVarSpeed_FB
VAR_INPUT
	Run			:	BOOL;
	Direction	:	BOOL;
	ConstSpeed	:	BOOL;
	Velocity	:	INT;
END_VAR
VAR_OUTPUT
	isRunning	:	BOOL;
	iActualVel	:	INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MotorVarSpeed_FB">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>